### ISSUE TITLE
create graphCreator class in graphCreator.py

### ISSUE THREAD

**Issue by Aimzj** [KenanKarav/ReGenesis#11]
An intermediary class.

The player will choose to plot a graph and a GUI relating to the chosen graph will appear.

The graphCreator will call the importFile class when importing the respective files needed for the creation of the graph.

The importing of a phenotype file will be optional.

GUI dropdown boxes will be used for the user to select which columns in the imported file they wish to analyse.

The graph  will be plotted when the "create" button is clicked.

**Comment by KenanKarav** [comment]
closed to split into separate creators for each graph
